### PR TITLE
Update transcrypt version and update python requirement to 3.7.

### LINKED ISSUE #14: Broken with python 3.7
Async has become a keyword with python 3.7, which breaks Transcrypt 

https://github.com/QQuick/Transcrypt/issues/543

### PR DESCRIPTION
**Pull request by daboross**
This should fix #14. However, I have not done extensive testing!

If you'd like to test this, just edit your local `requirements.txt`, then delete or rename `env/` to force `build.py` to re-download transcrypt.

`requirements.txt` should be:

```
git+git://github.com/daboross/Transcrypt.git@import-export-attempt-1#egg=transcrypt
```

You'll also want to copy the changes to `build.py`. The new one in this PR is at https://raw.githubusercontent.com/daboross/screeps-starter-python/update-transcrypt/build.py.

---

To undo, just delete/rename `env` again and undo the changes to `requirements.txt` and `build.py`.

### CODE REVIEW

**Comment by daboross** [comment]
I have this _somewhat_ working now!

Any python modules Transcrypt has written in JavaScript will likely fail since what I'm doing is quite hacky, but I got the starter running!

image

**Comment by ash-O-o** [comment]
@daboross Is there likely to be any further movement on this PR and/or repo? Seems you've moved on to mostly working on your rust projects for the last few months. 😄

**Comment by daboross** [comment]
@ash-O-o

It... could go forward, but I'm at a small impass in that I don't know what would be best for this project.

The main problem is that the new version of transcrypt outputs JavaScript files using "import" syntax, which is mainly only imported in other javascript pre-processors. 

There are a few ways this could go, mainly:

1. we add a dependency on node.js, and use a packing system alongside transcrypt's new system.
   
   This would be the least hacky solution, but I don't know how it would affect windows users. I mainly do everything on linux, and thus this would be fine for me, but I'm not sure about how well it interacts with other things, especially 

   The other disadvantage is that this keeps our current "one file" output. Not really a bad thing, but outputting mulltiple files which correctly require eachother could make on-the-fly edits and debugging much nicer.

2. we hack on transcrypt until we get it to output exactly the files we want

   This is pretty hacky, but could end up working well. If we go this way, I would want to do a lot more testing before merging into the repository (which I have not done).

   We could keep transcrypt outputting multiple files this way, and get python 3.7 without requiring a node.js dependency.

   This PR currently implements this strategy.


At this point I'm leaning towards depending on node.js, but I resisted for a while. One really nice thing about this project when I started it was that it _just_ required a python install, and could publish to screeps without any local JavaScript code.

If we do depend on node, we might as well get rid of build.py as well, or at least greatly reduce its responsibilities, and just use one of the more widespread and tested node.js deployment solutions like https://github.com/screeps/grunt-screeps. It'd make this project a much smaller one, but would make it technically more annoying to install because of the node.js/python dual dependency.

**Comment by tvardero** [comment]
i might be new in programming and stuff, but i got few errors that were persist in older version of build.py:
> You'll also want to copy the changes to build.py. The new one in this PR is at https://raw.githubusercontent.com/daboross/screeps-starter-python/update-transcrypt/build.py.

First issue i got is that token auth is not supported, i can auth only with email/login-password pair.
(build.py throws an error that "password" wasn't found in config.json file)

Second issue i got with new build.py is on line 281, checking python version fails somehow. I just removed that line and all worked. I can recreate this bug only if env folder is removed.
`(screeps) D:\Programs\Games\ScreepsPython>python build.py
creating virtualenv environment...
The path python3.7 (from --python=python3.7) does not exist
Traceback (most recent call last):
  File "build.py", line 345, in <module>
    main()
  File "build.py", line 334, in main
    install_env(config)
  File "build.py", line 290, in install_env
    .format(ret, "' '".join(args), config.base_dir))
Exception: virtualenv failed. exit code: 3. command line 'C:\Users\tvard\.conda\envs\screeps\python.exe' '-m' 'virtualenv' '-p' 'python3.7' '--system-site-packages' 'D:\Programs\Games\ScreepsPython\env'. working dir: 'D:\Programs\Games\ScreepsPython'.`

Third issue i got with new build.py is that shutil doesn't have copy_file() method, only copy(). Using copy() method on line 182 works fine and fixes it.

Fourth is:
`copying artifacts...
Traceback (most recent call last):
  File "build.py", line 345, in <module>
    main()
  File "build.py", line 340, in main
    build(config)
  File "build.py", line 203, in build
    copy_artifacts(config)
  File "build.py", line 189, in copy_artifacts
    source = scan.path
AttributeError: 'nt.ScandirIterator' object has no attribute 'path'`

Copying this codeblock from older version works fine. https://github.com/daboross/screeps-starter-python/blob/bdd4c015e9986253608dc8d844e49fc7f33514f7/build.py#L187

**Comment by daboross** [comment]
Superseded by #33.

**Comment by daboross** [comment]
@tvardero Sorry I missed your comment!

I think most of your issues should be resolved by updates since you wrote that comment. If there are still problems, please respond or open a new issue.

**Pull request closed without merging**
